### ISSUE TITLE
live session stuck at login page

### ISSUE THREAD

**Issue by thyeun** [peux-os-sic/Peux-river-2203#1]
Cant login with the below `username` and `password`. It will keep on back to the login page
```
Username : liveuser
Password : root
```
Try using tty to launch `river`, getting an error below
```
info: initializing server
info(wlroots): [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No suck file or directory
info(wlroots): [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
``` 

Any solution to get into the live session?

**Comment by DN-debug** [comment]
> Cant login with the below `username` and `password`. It will keep on back to the login page
> 
> ```
> Username : liveuser
> Password : root
> ```
> 
> Try using tty to launch `river`, getting an error below
> 
> ```
> info: initializing server
> info(wlroots): [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No suck file or directory
> info(wlroots): [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
> ```
> 
> Any solution to get into the live session?

Sorry didn't see ur text. Are you trying to launch it inside of a VM?

**Comment by thyeun** [comment]
@DN-debug In a PC.

**Comment by DN-debug** [comment]
> @DN-debug In a PC.

Interesting, I just tested the live-iso, it works for me. Could you try this : 
1. Again go to tty
2. ~~sudo~~ nano ~/.config/river/init
3. Add the below line : 
`riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND _DISPLAY XDG_CURRENT_DESKTOP=river"`

4. Ctrl+o to write the file, ctrl+s to save it. Ctrl+x to quit
5. rerun the `river` command. 

Lets see if that works or not! ( Do not use sudo, I typed that in a hurry )

**Comment by thyeun** [comment]
Still same error message.

I also been trying the below too, but i getting a blue screen as like hanging there without go into the riverwm. But without the error message

Below is what i try
1. Go to tty
2. Key-in export LIBSEAT_BACKEND=logind
3. Rerun river command
![IMG_20220412_152436.jpg](https://user-images.githubusercontent.com/1939446/162904388-ee34ca3c-8774-401c-9fe7-bd6f6f54b40b.jpg)

p/s : sorry that, reply you from smartphone, for easy to attach the screenshot.

**Comment by DN-debug** [comment]
can you try with `dbus-run-session river` ?

**Comment by thyeun** [comment]
Same error, hang at the blue screen, with error message from my first post

**Comment by thyeun** [comment]
@DN-debug This error it is because of the display driver that not supported by your live session? if yes, maybe that the issue, because my laptop are very very old and the display is hybrid radeon/intel.

**Comment by DN-debug** [comment]
> @DN-debug This error it is because of the display driver that not supported by your live session? if yes, maybe that the issue, because my laptop are very very old and the display is hybrid radeon/intel.

Display drivers ( except NVIDIA ) should pretty much work. To check which one of the two drivers is currently in use : `lspci -v`

There was another person who reported a similar issue, he never came back with an answer though. Wayland has a bad reputation in rendering the display. How far the hybrid system would work is still unknown. If one solution works, the other fails. 

How about checking the SWAY-ISO, and see whether that fails too or not?

If you already have an arch-based distro on your laptop, you can pull these dotfiles and then test it.

**Comment by thyeun** [comment]
@DN-debug My current system are not wayland :), that is why your riverwm get me interested to test is out :). i scare wayland will crash my system :)

Forgot to mention, I also tried include ```radeon.modeset=0``` at grub before it boot into login page. But the result still hang at blue screen or not possible to login with ```liveuser```

**Comment by DN-debug** [comment]
Wayland is unstable, sway is the most stable in Wayland window managers, using the term stable is from Wayland perspective, but stable is far-fetched. 

The reason I don't think it is AMD's problem ( hence didn't mention radeon.modeset=0 ) is because the other person that I talked about was using Intel generic graphics. 

Last try could be to append the user to pre-systemd group called video using : `usermod -a -G video $USER` 
If that doesn't work, then I will have to do more research on it, or probably open an issue with RiverWM. 

BTW, river have had such type of issue posted previously: [link to river Issue](https://github.com/riverwm/river/issues/438)

**Comment by thyeun** [comment]
@DN-debug Actually i try out many things, just i feel it is not related, that why not listed it out here.

From the tty, i create a new user also, instead of using the ```liveuser```, and i done also ```usermod -a -G video $USER```

Try out.
1. First try is same like my first post here 
2. Second try i include ```LIBSEAT_BACKEND=logind``` 
3. Third try based on your suggestion to add the wayland session inside ```init```.

Result as below
```First result```
```
info: initializing server
info(wlroots): [libseat] [libseat/backend/seatd.c:80] Could not connect to socket /run/seatd.sock: No suck file or directory
info(wlroots): [libseat] [libseat/libseat.c:76] Backend 'seatd' failed to open seat, skipping
```

```Second Result```
1. Hang at blue screen page
2. No error message 

```Third Result```
1. Hang at blue screen page
2.  With error message same as ```First Result```

**Comment by DN-debug** [comment]
Then I am afraid it won't work, **_or the way around is not yet known to me tbh_**. You might want to :
1. Open an issue with River team, and ask for their suggestion ( follow the link that I provided above or open a fresh issue altogether )
2. Or wait a little longer to see how River improves.
3. If you have another system to try it on, you can make an attempt there.

I will keep this post open for couple for days. You can always let me know about the possible solution if you get any, I will include  bit of code OR write that in a blog post for others.

**Comment by thyeun** [comment]
@DN-debug Is ok, just want to fill up my knowledge on wayland tilling window manager, and ```peux-os riverwm``` look nice. i will try again once ```riverwm``` more mature. And thanks!!!

**Comment by liamtimms** [comment]
Confirming this is an issue in VMs as well.
